import {
  color,
  direction,
  lineHeight,
  letterSpacing,
  textAlign,
  textDecoration,
  textIndent,
  textShadow,
  textTransform,
  textOverflow,
  unicodeBidi,
  whiteSpace,
  wordSpacing,
} from './textFunctions';

export const textFunctions = [
  color,
  direction,
  lineHeight,
  letterSpacing,
  textAlign,
  textDecoration,
  textIndent,
  textShadow,
  textTransform,
  textOverflow,
  unicodeBidi,
  whiteSpace,
  wordSpacing,
];
